// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.9.0
// source: heartBeat.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//心跳时间
type HeartBeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	AppCode      string `protobuf:"bytes,2,opt,name=appCode,proto3" json:"appCode,omitempty"`
	Channel      string `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	PlatformType string `protobuf:"bytes,4,opt,name=platformType,proto3" json:"platformType,omitempty"`
	BuildNumber  int32  `protobuf:"varint,5,opt,name=buildNumber,proto3" json:"buildNumber,omitempty"`
}

func (x *HeartBeat) Reset() {
	*x = HeartBeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_heartBeat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartBeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeat) ProtoMessage() {}

func (x *HeartBeat) ProtoReflect() protoreflect.Message {
	mi := &file_heartBeat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeat.ProtoReflect.Descriptor instead.
func (*HeartBeat) Descriptor() ([]byte, []int) {
	return file_heartBeat_proto_rawDescGZIP(), []int{0}
}

func (x *HeartBeat) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *HeartBeat) GetAppCode() string {
	if x != nil {
		return x.AppCode
	}
	return ""
}

func (x *HeartBeat) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *HeartBeat) GetPlatformType() string {
	if x != nil {
		return x.PlatformType
	}
	return ""
}

func (x *HeartBeat) GetBuildNumber() int32 {
	if x != nil {
		return x.BuildNumber
	}
	return 0
}

var File_heartBeat_proto protoreflect.FileDescriptor

var file_heartBeat_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x68, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x9d, 0x01, 0x0a, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x42,
	0x65, 0x61, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x70, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70,
	0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12,
	0x22, 0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_heartBeat_proto_rawDescOnce sync.Once
	file_heartBeat_proto_rawDescData = file_heartBeat_proto_rawDesc
)

func file_heartBeat_proto_rawDescGZIP() []byte {
	file_heartBeat_proto_rawDescOnce.Do(func() {
		file_heartBeat_proto_rawDescData = protoimpl.X.CompressGZIP(file_heartBeat_proto_rawDescData)
	})
	return file_heartBeat_proto_rawDescData
}

var file_heartBeat_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_heartBeat_proto_goTypes = []interface{}{
	(*HeartBeat)(nil), // 0: pb.heartBeat
}
var file_heartBeat_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_heartBeat_proto_init() }
func file_heartBeat_proto_init() {
	if File_heartBeat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_heartBeat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartBeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_heartBeat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_heartBeat_proto_goTypes,
		DependencyIndexes: file_heartBeat_proto_depIdxs,
		MessageInfos:      file_heartBeat_proto_msgTypes,
	}.Build()
	File_heartBeat_proto = out.File
	file_heartBeat_proto_rawDesc = nil
	file_heartBeat_proto_goTypes = nil
	file_heartBeat_proto_depIdxs = nil
}
