// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.9.0
// source: sendContinuousMsg.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//发送群发消息
type SendContinuousMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	AppCode      string   `protobuf:"bytes,2,opt,name=appCode,proto3" json:"appCode,omitempty"`
	Channel      string   `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	PlatformType string   `protobuf:"bytes,4,opt,name=platformType,proto3" json:"platformType,omitempty"`
	BuildNumber  int32    `protobuf:"varint,5,opt,name=buildNumber,proto3" json:"buildNumber,omitempty"`
	ToUserId     []string `protobuf:"bytes,6,rep,name=toUserId,proto3" json:"toUserId,omitempty"`
	MsgContent   string   `protobuf:"bytes,7,opt,name=msgContent,proto3" json:"msgContent,omitempty"`
}

func (x *SendContinuousMsg) Reset() {
	*x = SendContinuousMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sendContinuousMsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendContinuousMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendContinuousMsg) ProtoMessage() {}

func (x *SendContinuousMsg) ProtoReflect() protoreflect.Message {
	mi := &file_sendContinuousMsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendContinuousMsg.ProtoReflect.Descriptor instead.
func (*SendContinuousMsg) Descriptor() ([]byte, []int) {
	return file_sendContinuousMsg_proto_rawDescGZIP(), []int{0}
}

func (x *SendContinuousMsg) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendContinuousMsg) GetAppCode() string {
	if x != nil {
		return x.AppCode
	}
	return ""
}

func (x *SendContinuousMsg) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *SendContinuousMsg) GetPlatformType() string {
	if x != nil {
		return x.PlatformType
	}
	return ""
}

func (x *SendContinuousMsg) GetBuildNumber() int32 {
	if x != nil {
		return x.BuildNumber
	}
	return 0
}

func (x *SendContinuousMsg) GetToUserId() []string {
	if x != nil {
		return x.ToUserId
	}
	return nil
}

func (x *SendContinuousMsg) GetMsgContent() string {
	if x != nil {
		return x.MsgContent
	}
	return ""
}

var File_sendContinuousMsg_proto protoreflect.FileDescriptor

var file_sendContinuousMsg_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x6f, 0x75, 0x73,
	0x4d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xe1, 0x01,
	0x0a, 0x11, 0x73, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x6f, 0x75, 0x73,
	0x4d, 0x73, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x70, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70,
	0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12,
	0x22, 0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x74, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x73, 0x67, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x73, 0x67, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sendContinuousMsg_proto_rawDescOnce sync.Once
	file_sendContinuousMsg_proto_rawDescData = file_sendContinuousMsg_proto_rawDesc
)

func file_sendContinuousMsg_proto_rawDescGZIP() []byte {
	file_sendContinuousMsg_proto_rawDescOnce.Do(func() {
		file_sendContinuousMsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_sendContinuousMsg_proto_rawDescData)
	})
	return file_sendContinuousMsg_proto_rawDescData
}

var file_sendContinuousMsg_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sendContinuousMsg_proto_goTypes = []interface{}{
	(*SendContinuousMsg)(nil), // 0: pb.sendContinuousMsg
}
var file_sendContinuousMsg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sendContinuousMsg_proto_init() }
func file_sendContinuousMsg_proto_init() {
	if File_sendContinuousMsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sendContinuousMsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendContinuousMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sendContinuousMsg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sendContinuousMsg_proto_goTypes,
		DependencyIndexes: file_sendContinuousMsg_proto_depIdxs,
		MessageInfos:      file_sendContinuousMsg_proto_msgTypes,
	}.Build()
	File_sendContinuousMsg_proto = out.File
	file_sendContinuousMsg_proto_rawDesc = nil
	file_sendContinuousMsg_proto_goTypes = nil
	file_sendContinuousMsg_proto_depIdxs = nil
}
