// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.9.0
// source: userOnlineHomeMsg.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//心跳时间
type UserOnlineHomeMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *UserOnlineHomeMsg) Reset() {
	*x = UserOnlineHomeMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userOnlineHomeMsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserOnlineHomeMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOnlineHomeMsg) ProtoMessage() {}

func (x *UserOnlineHomeMsg) ProtoReflect() protoreflect.Message {
	mi := &file_userOnlineHomeMsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOnlineHomeMsg.ProtoReflect.Descriptor instead.
func (*UserOnlineHomeMsg) Descriptor() ([]byte, []int) {
	return file_userOnlineHomeMsg_proto_rawDescGZIP(), []int{0}
}

func (x *UserOnlineHomeMsg) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_userOnlineHomeMsg_proto protoreflect.FileDescriptor

var file_userOnlineHomeMsg_proto_rawDesc = []byte{
	0x0a, 0x17, 0x75, 0x73, 0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x48, 0x6f, 0x6d, 0x65,
	0x4d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x2b, 0x0a,
	0x11, 0x75, 0x73, 0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x48, 0x6f, 0x6d, 0x65, 0x4d,
	0x73, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_userOnlineHomeMsg_proto_rawDescOnce sync.Once
	file_userOnlineHomeMsg_proto_rawDescData = file_userOnlineHomeMsg_proto_rawDesc
)

func file_userOnlineHomeMsg_proto_rawDescGZIP() []byte {
	file_userOnlineHomeMsg_proto_rawDescOnce.Do(func() {
		file_userOnlineHomeMsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_userOnlineHomeMsg_proto_rawDescData)
	})
	return file_userOnlineHomeMsg_proto_rawDescData
}

var file_userOnlineHomeMsg_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_userOnlineHomeMsg_proto_goTypes = []interface{}{
	(*UserOnlineHomeMsg)(nil), // 0: pb.userOnlineHomeMsg
}
var file_userOnlineHomeMsg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_userOnlineHomeMsg_proto_init() }
func file_userOnlineHomeMsg_proto_init() {
	if File_userOnlineHomeMsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_userOnlineHomeMsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserOnlineHomeMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_userOnlineHomeMsg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_userOnlineHomeMsg_proto_goTypes,
		DependencyIndexes: file_userOnlineHomeMsg_proto_depIdxs,
		MessageInfos:      file_userOnlineHomeMsg_proto_msgTypes,
	}.Build()
	File_userOnlineHomeMsg_proto = out.File
	file_userOnlineHomeMsg_proto_rawDesc = nil
	file_userOnlineHomeMsg_proto_goTypes = nil
	file_userOnlineHomeMsg_proto_depIdxs = nil
}
